config/routes.rb
Rails.application.routes.draw do
  
  post '/create/showBook/:id',  to: 'create#showBook', as: 'loadBookView'
  post '/create/addThing'
  post '/create/convert'
  get    '/create', to: 'create#index'
  get    '/connect', to: 'connection#index'
  get    '/connect/add/:id', to: 'connection#addFriend', as: 'addFriend'
  get    '/connect/remove/:id', to: 'connection#removeFriend', as: 'removeFriend'
  get    '/home', to: 'dashboard#home'
  get    '/profile/:id', to: 'users#index', as: 'viewProfile'
  get    '/profile', to: 'users#edit', as: 'editProfile'
  get    '/updateUser', to: 'users#updateUser', as: 'update_user'
  post '/profile/create', to: 'users#createProfile', as: 'create_new_profile'
  put '/profile/update/:id', to: 'users#updateProfile', as: 'put_profile'
  patch '/profile/update/:id', to: 'users#updateProfile', as: 'patch_profile'
  get   '/dashboard',  to: 'dashboard#index'
  post   '/newstatus',  to: 'dashboard#newStatus'
  get   '/signin',  to: 'users#signIn'
  get   '/linkedIn/signin',  to: 'users#signInWithLinkedIn'
  get   '/github/signin',  to: 'users#signInWithGithub'
  get   '/google/signin',  to: 'users#signInWithGoogle'
  get   '/authLinkedIn',  to: 'users#linkedInAuthRedirect', as: 'auth_linked_in'
  get   '/authGithub',  to: 'users#githubAuthRedirect', as: 'auth_github'
  get   '/authGoogle',  to: 'users#googleAuthRedirect', as: 'auth_google'
  post  '/signin',  to: 'users#createSession', params: { session: { username: "", password: "" } }
  get   '/signout',  to: 'users#destroySession'
  get   '/signup',  to: 'users#signUp'
  post  '/signup',  to: 'users#createUser'
  put   '/account/update', to: 'users#putUser', as: 'put_user'
  delete    '/account/delete/:id', to: 'users#destroyUser', as: 'delete_user'
  match ':controller(/:action(/:id))', :via => :get

  root 'dashboard#landingpage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :profile
  belongs_to :firm
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :profile
  belongs_to :firm
end

app/models/firm.rb
class Firm < ApplicationRecord
  belongs_to :firmtype
  has_many :education, :dependent => :destroy
  has_many :experience, :dependent => :destroy
end

app/models/firmtype.rb
class Firmtype < ApplicationRecord
    has_many :firm, :dependent => :destroy
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, class_name: "User"
end

app/models/github_profile.rb
class GithubProfile < ApplicationRecord
  belongs_to :user
end

app/models/linkedin_profile.rb
class LinkedinProfile < ApplicationRecord
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
  has_many :education, :dependent => :destroy
  accepts_nested_attributes_for :education, allow_destroy: true, update_only: true
  has_many :experience, :dependent => :destroy
  accepts_nested_attributes_for :experience, allow_destroy: true, update_only: true
  has_many :speciality, :dependent => :destroy
  accepts_nested_attributes_for :speciality, allow_destroy: true, update_only: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :profile
end

app/models/speciality.rb
class Speciality < ApplicationRecord
    belongs_to :profile
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :user
end

app/models/sub_section.rb
class SubSection < ApplicationRecord
  belongs_to :section
end

app/models/thing.rb
class Thing < ApplicationRecord
  belongs_to :user
  belongs_to :thingtype
end

app/models/thingtype.rb
class Thingtype < ApplicationRecord
    has_many :thing, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_one :profile, :dependent => :destroy
    has_many :thing, :dependent => :destroy
    has_many :status, :dependent => :destroy

    validates :username, presence: true, length: { minimum: 4 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: 'is invalid'} 
    
    validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    if session[:username]
      @user = User.find_by(id: session[:user_id])
      if !@user.confirmed_profiles
        redirect_to update_user_path
      end
      @userStatus = Status.where(:user_id => session[:user_id]).order('id desc')
      @status = Status.new
    else
      redirect_to root_path
    end
  end

  def home
    redirect_to root_path
  end

  def landingPage
    
  end

  def newStatus
    @status = Status.new(status_params)
    @status.user_id = session[:user_id]
    @status.status_type = 1

    if @status.status != ""
      respond_to do |format|
        if @status.save
          format.html { redirect_to dashboard_path, notice: 'Status updated.' }
        else
          format.html { render :index }
          format.json { render json: @status.errors, status: :unprocessable_entity }
        end
      end
    else 
      redirect_to dashboard_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
        params.require(:status).permit(:status, :thing_id, :user_id)
    end  
end

app/helpers/connection_helper.rb
module ConnectionHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<p id="notice">
    <%= notice %>
</p>

<div class="lapor-dashboard-main">
    <div class="lapor-userbox">
        <div class="lapor-userbox-default-height lapor-userbox-get-height">
            <div class="lapor-userbox-profile">
                <% if @user.profile == nil || @user.profile.profile_picture == '' || @user.profile.profile_picture == nil %>
                    <%= image_tag "web_assets/anonymous/profile_male.jpg", :class => "lapor-profile-resize" %>
                <% else %>
                    <%= image_tag @user.profile.profile_picture, :class => "lapor-profile-resize"  %>
                <% end %>
            </div>
            <h1 class="lapor-userbox-name"><%= session[:username] %></h1>
        </div>
        <div class="lapor-userbox-default-height lapor-userbox-get-height">
            <% if @user.profile != nil && @user.profile.lifemotto != nil && @user.profile.lifemotto != '' %>
                <i>"<%= @user.profile.lifemotto %>"</i>
            <% end %>
        </div>
        <div class="lapor-userbox-get-height lapor-userbox-detail">
            <% if @user.email != nil && @user.email != '' %>
                <div>
                    <i class="fas fa-envelope"></i>
                    <span>
                        <%= @user.email %>
                    </span>
                </div>
            <% end %>
            <% if @user.profile != nil && @user.profile.phone != '' && @user.profile.phone != nil %>
                <div>
                    <i class="fas fa-phone"></i>
                    <span>
                        <%= @user.profile.phone %>
                    </span>
                </div>
            <% end %>
            <% if @user.profile != nil && @user.profile.address != '' && @user.profile.address != nil %>
                <div>
                    <i class="fas fa-map-marker-alt"></i>
                    <span>
                        <%= @user.profile.address %>
                    </span>
                </div>
            <% end %>
        </div>
        <div class="lapor-profile-height-trigger">
            <i class="fas fa-angle-down"></i>
        </div>
    </div>
    <div class="lapor-twitbox">
        <%= form_for(:status, url: newstatus_path(@status), local: true) do |form| %>
            <div class="lapor-twitbox-form">
                <%= form.text_area(:status, :id => "statusTwitbox", :placeholder => "Write your thoughts..", :cols => "70", :maxlength => "500", :class => "lapor-twitbox-input") %>
                <div class="lapor-twitbox-form-accessories">
                    <div id="statusCount">0/500</div>
                    <%= form.submit "Post", class: 'lapor-twitbox-small-button' %>
                </div>
            </div>
        <% end %>
        <% if @userStatus != nil %>
            <% @userStatus.each do |status| %>
                <div class="lapor-twitbox-space-circles"></div>
                <div class="lapor-twitbox-status-box">
                    <% if status.status_type == 2 %>
                        <%= @user.username %>
                    <% end %>
                    <%= status.status %>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

<script>
    var statusTwitbox = document.getElementById("statusTwitbox");
    statusTwitbox.value = "";

    function countChar(val) {
        statusTwitbox.style.height = statusTwitbox.scrollHeight + "px";
        statusTwitbox.style.overflow = "hidden";
        var len = val.length;
        if (len > 500) {
            val = val.substring(0, 500);
        } else {
            $('#statusCount').text(len + '/500');
            if(len > 450 && len <= 500){
                $('#statusCount').css("color", "red");
            }
            else{
                $('#statusCount').css("color", "#282828");
            }
        }
    };
    $('#statusTwitbox').on('keyup', function() {
        countChar($('#statusTwitbox').val());
    });
    $('#statusTwitbox').on('keypress', function() {
        countChar($('#statusTwitbox').val());
    });
    
    var notice = document.getElementById('notice');
    notice.style.display="none";
    var Toast = Swal.mixin({
        toast: true,
        position: 'bottom-end',
        showConfirmButton: false,
        timer: 3000
    })
    if(notice.innerText.trim()!=""){
        Toast.fire({
            type: 'success',
            title: notice.innerText
        })
    }

    var userBox = document.getElementsByClassName('lapor-userbox');
    var userBoxHeight = [];
    var userBoxDefaultHeight = [];
    var userBoxInnerContainer = []
    var userBoxDefaultInnerContainer = []
    for(let i = 0; i < userBox.length; i++){
        userBoxInnerContainer.push(userBox[i].getElementsByClassName('lapor-userbox-get-height'));
        userBoxDefaultInnerContainer.push(userBox[i].getElementsByClassName('lapor-userbox-default-height'));
    }
    var innerContainerStyle;
    
    function setUserBoxHeight(){
        for(let j = 0; j < userBox.length; j++){
            userBoxHeight[j] = 0;
            for(let i = 0; i < userBoxInnerContainer[j].length; i++){
                userBoxHeight[j] += userBoxInnerContainer[j][i].clientHeight;
                if(i > 0){
                    innerContainerStyle = userBoxInnerContainer[j][i].currentStyle || window.getComputedStyle(userBoxInnerContainer[j][i]);
                    userBoxHeight[j] += parseInt(
                        innerContainerStyle.marginTop.substr(0, 
                            innerContainerStyle.marginTop.lastIndexOf("px")
                        )
                    );
                    userBoxHeight[j] += parseInt(
                        innerContainerStyle.marginBottom.substr(0, 
                            innerContainerStyle.marginBottom.lastIndexOf("px")
                        )
                    );
                }
            }
            userBox[j].style.height = userBoxHeight[j].toString() + "px";
        }
    }

    function setUserBoxDefaultHeight(){
        for(let j = 0; j < userBox.length; j++){
            userBoxDefaultHeight[j] = 0;
            for(var i = 0; i < 2; i++){
                userBoxDefaultHeight[j] += userBoxDefaultInnerContainer[j][i].clientHeight;
                if(i == 1){
                    innerContainerStyle = userBoxDefaultInnerContainer[j][i].currentStyle || window.getComputedStyle(userBoxDefaultInnerContainer[j][i]);
                    userBoxDefaultHeight[j] += parseInt(
                        innerContainerStyle.marginTop.substr(0, 
                            innerContainerStyle.marginTop.lastIndexOf("px")
                        )
                    );
                    userBoxDefaultHeight[j] += parseInt(
                        innerContainerStyle.marginBottom.substr(0, 
                            innerContainerStyle.marginBottom.lastIndexOf("px")
                        )
                    );
                }
            }
            userBox[j].style.height = userBoxDefaultHeight[j].toString() + "px";
        }
    }
    setUserBoxDefaultHeight();

    function setSpecificUserBoxHeight(thisUserBox){
        let thisUserBoxHeight = 0;
        let thisUserBoxInnerContainer = thisUserBox.getElementsByClassName('lapor-userbox-get-height');
        for(let i = 0; i < thisUserBoxInnerContainer.length; i++){
            thisUserBoxHeight += thisUserBoxInnerContainer[i].clientHeight;
            if(i > 0){
                innerContainerStyle = thisUserBoxInnerContainer[i].currentStyle || window.getComputedStyle(thisUserBoxInnerContainer[i]);
                thisUserBoxHeight += parseInt(
                    innerContainerStyle.marginTop.substr(0, 
                        innerContainerStyle.marginTop.lastIndexOf("px")
                    )
                );
                thisUserBoxHeight += parseInt(
                    innerContainerStyle.marginBottom.substr(0, 
                        innerContainerStyle.marginBottom.lastIndexOf("px")
                    )
                );
            }
        }
        thisUserBox.style.height = thisUserBoxHeight.toString() + "px";
    }

    function setSpecificUserBoxDefaultHeight(thisUserBox){
        let thisUserBoxDefaultHeight = 0;
        let thisUserBoxInnerContainer = thisUserBox.getElementsByClassName('lapor-userbox-default-height');
        for(var i = 0; i < 2; i++){
            thisUserBoxDefaultHeight += thisUserBoxInnerContainer[i].clientHeight;
            if(i == 1){
                innerContainerStyle = thisUserBoxInnerContainer[i].currentStyle || window.getComputedStyle(thisUserBoxInnerContainer[i]);
                thisUserBoxDefaultHeight += parseInt(
                    innerContainerStyle.marginTop.substr(0, 
                        innerContainerStyle.marginTop.lastIndexOf("px")
                    )
                );
                thisUserBoxDefaultHeight += parseInt(
                    innerContainerStyle.marginBottom.substr(0, 
                        innerContainerStyle.marginBottom.lastIndexOf("px")
                    )
                );
            }
        }
        thisUserBox.style.height = thisUserBoxDefaultHeight.toString() + "px";
    }

    var laporUserBoxDetail = document.getElementsByClassName('lapor-userbox-detail');
    var toggleButton = document.getElementsByClassName('fa-angle-down');
    var toggleButtonUp;
    var toggeledUserBox;
    for(let i = 0; i < userBox.length; i++){
        toggleButton[i].onclick = function(){
            toggleButtonUp = document.getElementsByClassName('fa-angle-up');
            toggeledUserBox = toggleButton[i].parentNode.parentNode;
            if(toggleButtonUp.length === 0){
                laporUserBoxDetail[i].style.display = "block";
                setSpecificUserBoxHeight(toggeledUserBox);
                toggleButton[i].classList.add("fa-angle-up");
                setTimeout(function(){
                    laporUserBoxDetail[i].style.opacity = "1";
                }, 300)
            }
            else{
                for(let j = 0; j < toggleButtonUp.length; j++){
                    if(toggleButtonUp[j] == toggleButton[i]){
                        toggleButton[i].classList.remove("fa-angle-up");
                        setSpecificUserBoxDefaultHeight(toggeledUserBox);
                        laporUserBoxDetail[i].style.display = "none";
                        laporUserBoxDetail[i].style.opacity = "0";
                    }
                    else{
                        laporUserBoxDetail[i].style.display = "block";
                        setSpecificUserBoxHeight(toggeledUserBox);
                        toggleButton[i].classList.add("fa-angle-up");
                        setTimeout(function(){
                            laporUserBoxDetail[i].style.opacity = "1";
                        }, 300)
                    }
                }
            }
        }
    }

    window.onresize = function(){
        statusTwitbox.style.height =  0;
        statusTwitbox.style.height = statusTwitbox.scrollHeight + "px";
        statusTwitbox.style.overflow = "hidden";
        for(let i = 0; i < userBox.length; i++){
            let thisToggleButtonUp = userBox[i].getElementsByClassName("fa-angle-up");
            if(thisToggleButtonUp.length === 0){
                setSpecificUserBoxDefaultHeight(userBox[i]);
            }
            else{
                setSpecificUserBoxHeight(userBox[i]);
            }
        }
    }
</script>

app/views/dashboard/landingpage.html.erb
<style>
    .lapor-navbar{
        position: fixed;
        transform: translateY(-42px);
    }
    span.lapor-landing-page-title.lapor-alt-navbar-title{
        display: none;
    }
</style>

<div class="lapor-landing-page-navbar">
    <div class="lapor-landing-page-navbar-container">
        <%= link_to("PORTLUV", root_path, :class => 'lapor-landing-page-title lapor-red-font') %>
        <% if user_is_logged_in? %>
            <%= link_to("Dashboard", dashboard_path, :class => 'lapor-landing-page-button lapor-red-font') %>
        <% else %>
            <%= link_to("Sign Up", signup_path, :class => 'lapor-landing-page-button lapor-red-font') %>
        <% end %>
    </div>
</div>
<div class="lapor-landing-page-background">
    <div class="lapor-landing-page-background-desc">
        <h1>SAVE YOUR LIFE PROGRESS</h1>
        <span>
            <b>Keeping your achievements safe, while making you a profile to show off!</b> 
            <br />
            Upload your work, and see you progress through the times.
            <% if !user_is_logged_in? %>
                Register now for a free account.
            <% end %>
        </span>
        <% if user_is_logged_in? %>
            <%= link_to("Dashboard", dashboard_path, :class => 'lapor-landing-page-signup-button') %>
        <% else %>
            <%= link_to("Sign Up", signup_path, :class => 'lapor-landing-page-signup-button') %>
        <% end %>
    </div>
    <%= link_to("PORTLUV", root_path, :class => 'lapor-landing-page-title', :id => 'laporLandingTitle') %>
    <div class="slide-img"></div>
</div>

<h1 id="whatIs" class="lapor-landing-page-large-title">
    <span>
        WHAT IS PORTLUV?
    </span>
</h1>
<div class="lapor-landing-page-large-desc">
    Our goal is to make creative professionals have the coolest portfolio collection and to find these professionals equally cool jobs on our platform.
    PORTLUV is a website dedicated for these creative professionals, people who are willing to give their all. We keep their portfolio's safe whilst giving these professionals a profile worth showing. 
</div>

<h1 id="howTo" class="lapor-landing-page-large-title">
    <span>
        A SIMPLE GUIDE
    </span>
</h1>
<div class="lapor-landing-page-large-desc lapor-landing-page-card-container">
    <div class="lapor-how-to-card">
        <h4 style="text-align: center; margin-top: 12px; font-size: 14pt;">Register</h4>
        <div style="text-align: center; margin-top: 20px; margin-bottom: 40px;">
            <i class="fas fa-pencil-alt fa-7x"></i>
        </div>
        <hr>
        <span style="display: block; margin-top: 20px;">
            Before you use our app, please register to get access to our features
        </span>
    </div>
    <div class="lapor-how-to-card">
        <h4 style="text-align: center; margin-top: 12px; font-size: 14pt;">Upload Work</h4>
        <div style="text-align: center; margin-top: 20px; margin-bottom: 40px;">
            <i class="fas fa-file-upload fa-7x"></i>
        </div>
        <hr>
        <span style="display: block; margin-top: 20px;">
            Upload all of your best work in your Create page, and watch the magic happen!
        </span>
    </div>
    <div class="lapor-how-to-card">
        <h4 style="text-align: center; margin-top: 12px; font-size: 14pt;">Customize</h4>
        <div style="text-align: center; margin-top: 20px; margin-bottom: 40px;">
            <i class="fas fa-paint-brush fa-7x"></i>
        </div>
        <hr>
        <span style="display: block; margin-top: 20px;">
            After uploading your portfolio, add some little touches to your profile to make it more you!
        </span>
    </div>
</div>

<footer class="lapor-landing-page-footer">
    <div class="lapor-landing-page-footer-desc">
        <span>
            Create something awesome today!
        </span>
        <% if user_is_logged_in? %>
            <%= link_to("Dashboard", dashboard_path, :class => 'lapor-landing-page-signup-button lapor-landing-page-footer-signup-button') %>
        <% else %>
            <%= link_to("Sign Up", signup_path, :class => 'lapor-landing-page-signup-button lapor-landing-page-footer-signup-button') %>
        <% end %>
    </div>
    <span>
        Have a problem?
        Send an Email : portluv@gmail.com
    </span>
    <span class="lapor-landing-page-footer-title">PORTLUV - Copyright 2019</span>
</footer>

<script>
$(document).ready(function(){
    setTimeout(function(){
        $('.lapor-landing-page-background-desc').fadeIn('slow');  
    }, 500);
    var bindEvent = true;
    reachedWhatIs();
    function reachedTop(){
        $(document).bind('scroll', function() {
            if($(this).scrollTop()<$('#whatIs').position().top && bindEvent === false){
                reachedWhatIs();
                bindEvent = true;
                $('.lapor-landing-page-navbar').css("transform", "translateY(-48px)");
            }
        });
    }
    function reachedWhatIs(){
        $(document).bind('scroll', function() {
            if($(this).scrollTop()>=$('#whatIs').position().top && bindEvent === true){
                $(document).unbind();
                bindEvent = false;
                $('.lapor-landing-page-navbar').css("transform", "translateY(0px)");
                reachedTop();
            }
        });
    }
});
</script>

app/views/dashboard/profile.html.erb
<main id="laporBody" class="lapor-body">
    <div class="lapor-profile">
        <div class="lapor-profile-picture"></div>
        <h1 class="lapor-profile-name">Agustinus Theodorus</h1>
    </div>
</main>

<script>
    // setTimeout(function(){
    //     document.getElementById('laporNavbar').style.transform = 'translateY(-42px)';
    //     document.getElementById('laporBody').style.transform = 'translateY(-42px)';
    // }, 200);
</script>