config/routes.rb
Rails.application.routes.draw do
  
  post '/create/showBook/:id',  to: 'create#showBook', as: 'loadBookView'
  post '/create/addThing'
  post '/create/convert'
  get    '/create', to: 'create#index'
  get    '/connect', to: 'connection#index'
  get    '/connect/add/:id', to: 'connection#addFriend', as: 'addFriend'
  get    '/connect/remove/:id', to: 'connection#removeFriend', as: 'removeFriend'
  get    '/home', to: 'dashboard#home'
  get    '/profile/:id', to: 'users#index', as: 'viewProfile'
  get    '/profile', to: 'users#edit', as: 'editProfile'
  get    '/updateUser', to: 'users#updateUser', as: 'update_user'
  post '/profile/create', to: 'users#createProfile', as: 'create_new_profile'
  put '/profile/update/:id', to: 'users#updateProfile', as: 'put_profile'
  patch '/profile/update/:id', to: 'users#updateProfile', as: 'patch_profile'
  get   '/dashboard',  to: 'dashboard#index'
  post   '/newstatus',  to: 'dashboard#newStatus'
  get   '/signin',  to: 'users#signIn'
  get   '/linkedIn/signin',  to: 'users#signInWithLinkedIn'
  get   '/github/signin',  to: 'users#signInWithGithub'
  get   '/google/signin',  to: 'users#signInWithGoogle'
  get   '/authLinkedIn',  to: 'users#linkedInAuthRedirect', as: 'auth_linked_in'
  get   '/authGithub',  to: 'users#githubAuthRedirect', as: 'auth_github'
  get   '/authGoogle',  to: 'users#googleAuthRedirect', as: 'auth_google'
  post  '/signin',  to: 'users#createSession', params: { session: { username: "", password: "" } }
  get   '/signout',  to: 'users#destroySession'
  get   '/signup',  to: 'users#signUp'
  post  '/signup',  to: 'users#createUser'
  put   '/account/update', to: 'users#putUser', as: 'put_user'
  delete    '/account/delete/:id', to: 'users#destroyUser', as: 'delete_user'
  match ':controller(/:action(/:id))', :via => :get

  root 'dashboard#landingpage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_one :profile, :dependent => :destroy
    has_many :thing, :dependent => :destroy
    has_many :status, :dependent => :destroy

    validates :username, presence: true, length: { minimum: 4 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: 'is invalid'} 
    
    validates :password, presence: true, length: { minimum: 8 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:destroyUser]
  before_action :set_profile, only: [:updateProfile]

  def index
    @user = User.find_by(id: params[:id])
    if(@user.profile != nil)
      @profile = @user.profile
      if(@profile.education != nil)
        @education = @profile.education
      else
        @education = Education.new
      end
      if(@profile.experience != nil)
        @experience = @profile.experience
      else
        @experience = Experience.new
      end
    else
      @profile = Profile.new
      @education = Education.new
      @experience = Experience.new
    end
  end

  def edit
    if session[:username]
      @user = User.find_by(username: session[:username])
      if(@user.profile != nil)
        @profile = @user.profile
        if(@profile.education != nil)
          @education = @profile.education
        else
          @education = Education.new
        end
        if(@profile.experience != nil)
          @experience = @profile.experience
        else
          @experience = Experience.new
        end
      else
        @profile = Profile.new
        @education = Education.new
        @experience = Experience.new
      end
    else
      redirect_to root_path
    end
  end

  def signIn
    if session[:user_id]
      redirect_to dashboard_path
    end
  end

  def signUp
    if session[:user_id]
      redirect_to dashboard_path
    end
    @user = User.new
  end

  def createSession
    user = User.find_by(username: params[:session][:username], password: params[:session][:password])
    respond_to do |format|
      if user
          session[:user_id] = user.id
          session[:username] = user.username 
          format.html { redirect_to dashboard_path, notice: 'Sign in was successful.' }
      else
          format.html { redirect_to signin_path, notice: 'Sign in was unsuccessful.' }
      end
    end
  end

  def createUser
    @user = User.new(user_params)
    @user.confirmed_profiles = true
    @status = Status.new
    @status.status_type = 2
    @status.status = " created an account"
    user = User.find_by(username: @user.username)
    if user != nil
      usedUsername=true
    end
    user = User.find_by(email: @user.email)
    if user != nil
      usedEmail=true
    end
    respond_to do |format|
      if !usedUsername && !usedEmail && @user.save
        user = User.find_by(username: @user.username, password: @user.password)
        session[:user_id] = user.id
        session[:username] = user.username 
        @status.user_id = session[:user_id]
        @status.save
        format.html { redirect_to dashboard_path, notice: 'Sign up was successful.' }
      else
        if usedUsername
          @user.errors.add(:username, "Username already exist!")
        end
        if usedEmail
          @user.errors.add(:email, "Email is already used!")
        end
        format.html { render :signUp }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def updateUser
    @user = User.find_by(id: session[:user_id])
    @user.password = ""
  end

  def putUser
    @user = User.find_by(id: session[:user_id])
    @user.confirmed_profiles = true
    usedUsername=false
    usedEmail=false
    user = User.find_by(username: params[:username])
    if user != nil && user.id != @user.id
      usedUsername=true
    end
    user = User.find_by(email: params[:email])
    if user != nil && user.id != @user.id
      usedEmail=true
    end
    respond_to do |format|
      if !usedUsername && !usedEmail && @user.update(user_params)
        user = User.find_by(username: @user.username, password: @user.password)
        session[:user_id] = user.id
        session[:username] = user.username 
        format.html { redirect_to dashboard_path, notice: 'Update user was successful.' }
      else
        if usedUsername
          @user.errors.add(:username, "Username already exist!")
        end
        if usedEmail
          @user.errors.add(:email, "Email is already used!")
        end
        format.html { render :updateUser }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def linkedInAuthRedirect
    state_csrf = ('A'..'Z').to_a.shuffle[0,15].join
    redirect_uri=""
    if request.host == "localhost"
      redirect_uri=request.protocol + request.host_with_port
    else
      redirect_uri=request.protocol + request.host
    end

    redirect_uri+="/linkedIn/signin"
    link="https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id="+LINKEDIN_CLIENT_ID+"&redirect_uri="+redirect_uri+"&state="+state_csrf+"&scope=r_liteprofile%20r_emailaddress%20w_member_social"
    redirect_to link
  end

  def signInWithLinkedIn
    redirect_uri=""
    if request.host == "localhost"
      redirect_uri=request.protocol + request.host_with_port
    else
      redirect_uri=request.protocol + request.host
    end
    redirect_uri+=request.path
    
    params = {
      'grant_type' => 'authorization_code',
      'code' => request.GET["code"],
      'redirect_uri' => redirect_uri,
      'client_id' => LINKEDIN_CLIENT_ID,
      'client_secret' => LINKEDIN_CLIENT_SECRET,
    }
    res = HTTParty.post("https://www.linkedin.com/oauth/v2/accessToken",
      :body => params,
      :headers => {'Content-Type' => 'application/x-www-form-urlencoded'}
    )
    accessToken=res["access_token"]
    expireIn=Date.today
    expireIn+=res["expires_in"]/(60*60*24)

    res = HTTParty.get("https://api.linkedin.com/v2/me",
      :headers => {'Authorization' => 'Bearer '+accessToken}
    )
    linkedInProfileID=res["id"]
    
    linkedin_login = LinkedinProfile.find_by(linkedin_profile_id: linkedInProfileID)
    if linkedin_login
      linkedin_login.update(access_token: accessToken, expire_in: expireIn)
      user = User.find_by(id: linkedin_login.user_id)
      session[:user_id] = user.id
      session[:username] = user.username 
      flash[:notice] = 'Sign in was successful.'
      redirect_to dashboard_path
    else
      fullname=res["localizedFirstName"]+" "+res["localizedLastName"]
      res = HTTParty.get("https://api.linkedin.com/v2/emailAddress?q=members&projection=(elements*(handle~))",
        :headers => {'Authorization' => 'Bearer '+accessToken}
      )
      email=res["elements"][0]["handle~"]["emailAddress"]
      username = email.slice(0..(email.index('@')-1))
      
      usedEmail=false
      usedUsername=false
      @user = User.new
      @user.username=username+"-"+linkedInProfileID
      @user.email=email
      user = User.find_by(email: @user.username)
      if user != nil
        usedUsername=true
      end
      user = User.find_by(email: @user.email)
      if user != nil
        usedEmail=true
      end
      if !usedEmail && !usedUsername
        print("IIINNN")
        @user.password = ('A'..'Z').to_a.shuffle[0,15].join
        @user.save
        user = User.find_by(username: @user.username, password: @user.password)
        session[:user_id] = user.id
        session[:username] = user.username 
    
        @status = Status.new
        @status.user_id = session[:user_id]
        @status.status_type = 2
        @status.status = " created an account"
        @status.save
    
        @profile = Profile.new
        @profile.fullname=fullname
        @profile.user_id=user.id
        @profile.save
    
        @linkedinProfile = LinkedinProfile.new
        @linkedinProfile.access_token = accessToken
        @linkedinProfile.expire_in = expireIn
        @linkedinProfile.linkedin_profile_id=linkedInProfileID
        @linkedinProfile.user_id=user.id
        @linkedinProfile.save
      end
      
      respond_to do |format|
        if usedUsername || usedEmail
          format.html { redirect_to signin_path, notice: 'Sign in was unsuccessful.' }
        elsif user
            session[:user_id] = user.id
            session[:username] = user.username 
            format.html { redirect_to dashboard_path, notice: 'Sign in was successful.' }
        else
            format.html { redirect_to signin_path, notice: 'Sign in was unsuccessful.' }
        end
      end
    end
  end

  def githubAuthRedirect
    redirect_uri=""
    if request.host == "localhost"
      redirect_uri=request.protocol + request.host_with_port
    else
      redirect_uri=request.protocol + request.host
    end

    redirect_uri+="/github/signin"
    link="https://github.com/login/oauth/authorize?scope=user:email&client_id="+GITHUB_CLIENT_ID
    redirect_to link
  end

  def signInWithGithub
    redirect_uri=""
    if request.host == "localhost"
      redirect_uri=request.protocol + request.host_with_port
    else
      redirect_uri=request.protocol + request.host
    end
    redirect_uri+=request.path
    
    params = {
      'client_id' => GITHUB_CLIENT_ID,
      'client_secret' => GITHUB_CLIENT_SECRET,
      'code' => request.GET["code"],
    }
    res = HTTParty.post("https://github.com/login/oauth/access_token",
      :body => params,
      :headers => {
        'Content-Type' => 'application/x-www-form-urlencoded',
        'Accept' => 'application/json',
      }
    )
    
    accessToken=res["access_token"]
    scopes = res["scope"].split(',')
    res = HTTParty.get("https://api.github.com/user",
      :query => {'access_token' => accessToken}
    )
    
    githubProfileID=res["id"]
    
    github_login = GithubProfile.find_by(github_profile_id: githubProfileID)
    if github_login
      github_login.update(access_token: accessToken)
      user = User.find_by(id: github_login.user_id)
      session[:user_id] = user.id
      session[:username] = user.username 
      flash[:notice] = 'Sign in was successful.'
      redirect_to dashboard_path
    elsif scopes.include? 'user:email'
      email = HTTParty.get("https://api.github.com/user/emails",
        :query => {'access_token' => accessToken}
      )
      fullname=res["name"]
      email = email[0]["email"]

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_signin.html.erb
<%= form_for(:session, url: signin_path) do |form| %>
  <p id="notice"><%= notice %></p>
  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username, class: 'lapor-form-input' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password, class: 'lapor-form-input', type: 'password' %>
  </div>

  <div class="actions">
    <%= form.submit "Sign In", class: 'lapor-form-button' %>
    <div class="lapor-signin-button-divider">or</div>
    <a href="<%= auth_github_path %>" class='lapor-signin-github'>
      <%= image_tag "web_assets/logo/github.png", :class => "lapor-signin-logo" %>
      <span>Sign In with Github</span>
    </a>
    <a href="<%= auth_linked_in_path+'?type=signin' %>" class='lapor-signin-linkedin'>
      <%= image_tag "web_assets/logo/linkedin.png", :class => "lapor-signin-logo" %>
      <span>Sign In with LinkedIn</span>
    </a>
    <%= link_to 'Don\'t have an account? Sign Up Here!', signup_path %>
    <%= link_to 'Back to home', home_path %>
  </div>
<% end %>

<style>
  #laporNavbar{
    display: none;
  }
  .lapor-main{
    height: calc((100vh - var(--paddingSize)) - var(--navbarSize));
  }
  .lapor-landing-page-title{
    color: white;
  }
</style>

<script>
    var notice = document.getElementById('notice');
    notice.style.display="none";
    var Toast = Swal.mixin({
        toast: true,
        position: 'bottom-end',
        showConfirmButton: false,
        timer: 1500
    })
    if(notice.innerText.trim()!=""){
        Toast.fire({
            type: 'error',
            title: notice.innerText
        })
        notice.innerText="";
    }
</script>

app/views/users/_signup.html.erb
<%= form_with(model: user, url: signup_path(@user), local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul id="notice">
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username, class: 'lapor-form-input' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: 'lapor-form-input' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password, class: 'lapor-form-input', type: 'password' %>
  </div>

  <div class="actions">
    <%= form.submit "Sign Up", class: 'lapor-form-button' %>
    <div class="lapor-signin-button-divider">or</div>
    <a href="<%= auth_github_path %>" class='lapor-signin-github'>
      <%= image_tag "web_assets/logo/github.png", :class => "lapor-signin-logo" %>
      <span>Sign Up with Github</span>
    </a>
    <a href="<%= auth_linked_in_path+'?type=signin' %>" class='lapor-signin-linkedin'>
      <%= image_tag "web_assets/logo/linkedin.png", :class => "lapor-signin-logo" %>
      <span>Sign Up with LinkedIn</span>
    </a>
    <%= link_to 'Have an account? Sign In Here!', signin_path %>
    <%= link_to 'Back to home', home_path %>
  </div>
<% end %>

<style>
  #laporNavbar{
    display: none;
  }
  .lapor-main{
    height: calc((100vh - var(--paddingSize)) - var(--navbarSize));
  }
  .lapor-landing-page-title{
    color: white;
  }
</style>

<script>
    var notice = document.getElementById('notice');
    if(notice!=null){
      var errorList = notice.getElementsByTagName('li');
      var errorText = "";
      for(let i=0;i<errorList.length;i++){
        errorText+=errorList[i].innerText+'<br>';
      }
      if(notice.innerText.trim()!=""){
          Swal.fire({
            type: 'error',
            title: 'Error',
            html: '<br>'+errorText
          });
          notice.innerText="";
      }
    }
</script>

app/views/users/_updateUser.html.erb
<%= form_with(model: user, url: put_user_path, method: :put, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul id="notice">
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username, class: 'lapor-form-input' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: 'lapor-form-input' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password, class: 'lapor-form-input', type: 'password' %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'lapor-form-button' %>
  </div>
<% end %>

<style>
  #laporNavbar{
    display: none;
  }
  .lapor-main{
    height: calc((100vh - var(--paddingSize)) - var(--navbarSize));
  }
  .lapor-landing-page-title{
    color: white;
  }
</style>

<script>
    $(document).ready(function(){
      if($('#error_explanation').length==0){
        Swal.fire({
          type: 'warning',
          title: 'Hi!',
          html: 'Please update your generated user data before continuing',
        });
      }
    });
    var notice = document.getElementById('notice');
    if(notice!=null){
      var errorList = notice.getElementsByTagName('li');
      var errorText = "";
      for(let i=0;i<errorList.length;i++){
        errorText+=errorList[i].innerText+'<br>';
      }
      if(notice.innerText.trim()!=""){
          Swal.fire({
            type: 'error',
            title: 'Error',
            html: '<br>'+errorText
          });
          notice.innerText="";
      }
    }
</script>

app/views/users/_updateUserSignInWithGithub.html.erb
<%= form_with(model: user, url: put_user_path, method: :put, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul id="notice">
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :user_username, class: 'lapor-form-input' %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: 'lapor-form-input' %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password, class: 'lapor-form-input', type: 'password' %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: 'lapor-form-button' %>
  </div>
<% end %>

<style>
  #laporNavbar{
    display: none;
  }
  .lapor-main{
    height: calc((100vh - var(--paddingSize)) - var(--navbarSize));
  }
  .lapor-landing-page-title{
    color: white;
  }
</style>

<script>
    $(document).ready(function(){
      if($('#error_explanation').length==0){
        Swal.fire({
          type: 'warning',
          title: 'Hi!',
          html: 'Thank you for signing in using Github<br>Please update your generated user data before continuing',
        });
      }
    });
    var notice = document.getElementById('notice');
    if(notice!=null){
      var errorList = notice.getElementsByTagName('li');
      var errorText = "";
      for(let i=0;i<errorList.length;i++){
        errorText+=errorList[i].innerText+'<br>';
      }
      if(notice.innerText.trim()!=""){
          Swal.fire({
            type: 'error',
            title: 'Error',
            html: '<br>'+errorText
          });
          notice.innerText="";
      }
    }
</script>

app/views/users/edit.html.erb
<%= render 'editProfile', profile: @profile %>

app/views/users/new.html.erb
<div class="lapor-signup-content">
    <h1 class="lapor-signup-title">LadangPortfolio</h1>

    <div class="lapor-signup-form">
        <h1>Sign Up</h1>
        <%= render 'signup', user: @user %>
    </div>
</div>

app/views/users/show.html.erb
<div class="lapor-signup-content">
    <h1 class="lapor-signup-title">LadangPortfolio</h1>

    <div class="lapor-signup-form">
        <h1>Sign In</h1>
        <%= render 'signin', user: @user %>
    </div>
</div>

app/views/users/signIn.html.erb
<div class="lapor-signup-content">
<h1 class="lapor-signup-title">PORTLUV</h1>

<div class="lapor-signup-form">
    <h1>Sign In</h1>
    <%= render 'signin', user: @user %>
</div>
</div>

app/views/users/signUp.html.erb
<div class="lapor-signup-content">
    <h1 class="lapor-signup-title">PORTLUV</h1>

    <div class="lapor-signup-form">
        <h1>Sign Up</h1>
        <%= render 'signup', user: @user %>
    </div>
</div>

app/views/users/updateUser.html.erb
<div class="lapor-signup-content">
    <h1 class="lapor-signup-title">PORTLUV</h1>

    <div class="lapor-signup-form">
        <h1>Update User Data</h1>
        <%= render 'updateUser', user: @user %>
    </div>
</div>

app/views/users/updateUserSignInWithGithub.html.erb
<div class="lapor-signup-content">
    <h1 class="lapor-signup-title">PORTLUV</h1>

    <div class="lapor-signup-form">
        <h1>Update User Data</h1>
        <%= render 'updateUserSignInWithGithub', user: @user %>
    </div>
</div>