config/routes.rb
Rails.application.routes.draw do
  
  post '/create/showBook/:id',  to: 'create#showBook', as: 'loadBookView'
  post '/create/addThing'
  post '/create/convert'
  get    '/create', to: 'create#index'
  get    '/connect', to: 'connection#index'
  get    '/connect/add/:id', to: 'connection#addFriend', as: 'addFriend'
  get    '/connect/remove/:id', to: 'connection#removeFriend', as: 'removeFriend'
  get    '/home', to: 'dashboard#home'
  get    '/profile/:id', to: 'users#index', as: 'viewProfile'
  get    '/profile', to: 'users#edit', as: 'editProfile'
  get    '/updateUser', to: 'users#updateUser', as: 'update_user'
  post '/profile/create', to: 'users#createProfile', as: 'create_new_profile'
  put '/profile/update/:id', to: 'users#updateProfile', as: 'put_profile'
  patch '/profile/update/:id', to: 'users#updateProfile', as: 'patch_profile'
  get   '/dashboard',  to: 'dashboard#index'
  post   '/newstatus',  to: 'dashboard#newStatus'
  get   '/signin',  to: 'users#signIn'
  get   '/linkedIn/signin',  to: 'users#signInWithLinkedIn'
  get   '/github/signin',  to: 'users#signInWithGithub'
  get   '/google/signin',  to: 'users#signInWithGoogle'
  get   '/authLinkedIn',  to: 'users#linkedInAuthRedirect', as: 'auth_linked_in'
  get   '/authGithub',  to: 'users#githubAuthRedirect', as: 'auth_github'
  get   '/authGoogle',  to: 'users#googleAuthRedirect', as: 'auth_google'
  post  '/signin',  to: 'users#createSession', params: { session: { username: "", password: "" } }
  get   '/signout',  to: 'users#destroySession'
  get   '/signup',  to: 'users#signUp'
  post  '/signup',  to: 'users#createUser'
  put   '/account/update', to: 'users#putUser', as: 'put_user'
  delete    '/account/delete/:id', to: 'users#destroyUser', as: 'delete_user'
  match ':controller(/:action(/:id))', :via => :get

  root 'dashboard#landingpage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :profile
  belongs_to :firm
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :profile
  belongs_to :firm
end

app/models/firm.rb
class Firm < ApplicationRecord
  belongs_to :firmtype
  has_many :education, :dependent => :destroy
  has_many :experience, :dependent => :destroy
end

app/models/firmtype.rb
class Firmtype < ApplicationRecord
    has_many :firm, :dependent => :destroy
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user, class_name: "User"
end

app/models/github_profile.rb
class GithubProfile < ApplicationRecord
  belongs_to :user
end

app/models/linkedin_profile.rb
class LinkedinProfile < ApplicationRecord
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user, optional: true
  has_many :education, :dependent => :destroy
  accepts_nested_attributes_for :education, allow_destroy: true, update_only: true
  has_many :experience, :dependent => :destroy
  accepts_nested_attributes_for :experience, allow_destroy: true, update_only: true
  has_many :speciality, :dependent => :destroy
  accepts_nested_attributes_for :speciality, allow_destroy: true, update_only: true
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :profile
end

app/models/speciality.rb
class Speciality < ApplicationRecord
    belongs_to :profile
end

app/models/status.rb
class Status < ApplicationRecord
  belongs_to :user
end

app/models/sub_section.rb
class SubSection < ApplicationRecord
  belongs_to :section
end

app/models/thing.rb
class Thing < ApplicationRecord
  belongs_to :user
  belongs_to :thingtype
end

app/models/thingtype.rb
class Thingtype < ApplicationRecord
    has_many :thing, :dependent => :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_one :profile, :dependent => :destroy
    has_many :thing, :dependent => :destroy
    has_many :status, :dependent => :destroy

    validates :username, presence: true, length: { minimum: 4 }
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: 'is invalid'} 
    
    validates :password, presence: true, length: { minimum: 8 }
end

app/helpers/connection_helper.rb
module ConnectionHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portluv</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Kanit:700" rel="stylesheet">
    <script src="https://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <!-- The core Firebase JS SDK is always required and must be listed first -->
    <script src="https://www.gstatic.com/firebasejs/5.7.0/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.7.0/firebase-firestore.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-storage.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>
    <script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>
    <link href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css" /> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'web_assets/favicon.ico' %>
  </head>

  <body>
    <header id="laporNavbar" class="lapor-navbar"> 
        <%= link_to("DASHBOARD", dashboard_path, :class => 'lapor-navbar-item' ) %>
        <%= link_to("PROFILE", editProfile_path, :class => 'lapor-navbar-item') %>
        <%= link_to("CREATE", { :controller => 'create', :action => 'index'}, :class => 'lapor-navbar-item' ) %>
        <%= link_to("CONNECT", { :controller => 'connection', :action => 'index'}, :class => 'lapor-navbar-item' ) %>
        <% if user_is_logged_in? %>
          <%= link_to("SIGN OUT", signout_path, :class => 'lapor-navbar-item lapor-signin-button') %>
        <% else %>
          <%= link_to("SIGN IN", signin_path, :class => 'lapor-navbar-item lapor-signin-button') %>
        <% end %>
        <label class="lapor-burger-label" for="laporAltNavBarTrigger">
          <div></div>
          <div></div>
          <div></div>
        </label>
    </header>
    <span class="lapor-landing-page-title lapor-alt-navbar-title">PORTLUV</span>
    <input type="checkbox" id="laporAltNavBarTrigger" class="lapor-burger">
    <section class="lapor-alt-navbar">
        <%= link_to("DASHBOARD", dashboard_path, :class => 'lapor-alt-navbar-item' ) %>
        <%= link_to("PROFILE", editProfile_path, :class => 'lapor-alt-navbar-item') %>
        <%= link_to("CREATE", { :controller => 'create', :action => 'index'}, :class => 'lapor-alt-navbar-item' ) %>
        <%= link_to("CONNECT", { :controller => 'connection', :action => 'index'}, :class => 'lapor-alt-navbar-item' ) %>
        <% if user_is_logged_in? %>
          <%= link_to("SIGN OUT", signout_path, :class => 'lapor-alt-navbar-item') %>
        <% else %>
          <%= link_to("SIGN IN", signin_path, :class => 'lapor-alt-navbar-item') %>
        <% end %>
    </section>
    <% if current_page?(root_url) %>
      <main>
        <%= yield %>
      </main>
    <% else %>
      <main class="lapor-main">
        <%= yield %>
      </main>
    <% end %>
  </body>
</html>